/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Office(props) {
  const { nodes, materials } = useGLTF('/office.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Vert024.geometry} material={materials['Material.004']} position={[2.3, 0.33, 2.84]} rotation={[Math.PI, -1.13, Math.PI / 2]} scale={0.79} />
      <mesh geometry={nodes.Vert023.geometry} material={materials['Material.004']} position={[-2.68, 0.33, 2.85]} rotation={[0, -0.97, -Math.PI / 2]} scale={0.75} />
      <mesh geometry={nodes.Vert022.geometry} material={materials['Material.004']} position={[-0.34, 0.33, 2.83]} rotation={[0, -1.36, -Math.PI / 2]} />
      <mesh geometry={nodes.Vert021.geometry} material={materials['Material.003']} position={[-0.13, 0.84, -2.72]} />
      <mesh geometry={nodes.Vert020.geometry} material={materials['книга.001']} position={[3.82, 0.84, -2.61]} />
      <mesh geometry={nodes.Vert019.geometry} material={materials.ствол} position={[4.2, 0.84, -2.77]} />
      <mesh geometry={nodes.Vert018.geometry} material={materials['Material.004']} position={[4.56, 2.72, -3.67]} scale={[1.06, 0.69, 1.07]} />
      <mesh geometry={nodes.Vert017.geometry} material={materials['подставка .001']} position={[4.21, 2.72, -3.66]} scale={[1.06, 0.64, 1.07]} />
      <mesh geometry={nodes.Vert016.geometry} material={materials['Material.004']} position={[3.64, 2.66, -3.68]} scale={[1.06, 0.57, 1.07]} />
      <mesh geometry={nodes.Vert015.geometry} material={materials.дерево} position={[3.4, 2.71, -3.75]} scale={[1.06, 0.64, 1.07]} />
      <mesh geometry={nodes.Vert014.geometry} material={materials.книга1} position={[3.07, 2.62, -3.69]} scale={[1.06, 0.48, 1.07]} />
      <mesh geometry={nodes.Vert013.geometry} material={materials['книга.001']} position={[2.88, 2.72, -3.61]} scale={[1.06, 0.64, 1.07]} />
      <mesh geometry={nodes.Vert012.geometry} material={materials['Книга.001']} position={[2.65, 2.72, -3.67]} scale={[1.06, 0.73, 1.07]} />
      <mesh geometry={nodes.Vert011.geometry} material={materials.земля} position={[2.22, 2.66, -3.67]} scale={[1.06, 0.55, 1.07]} />
      <mesh geometry={nodes.Vert010.geometry} material={materials.Книга} position={[1.48, 2.72, -3.67]} scale={[1.06, 0.64, 1.07]} />
      <mesh geometry={nodes.Vert009.geometry} material={materials.горшок} position={[2.22, 2.77, -3.34]} rotation={[0.37, 0.3, -1.78]} scale={[1.05, 1, 1.06]} />
      <mesh geometry={nodes.Vert008.geometry} material={materials['Material.004']} position={[2, 2.41, -3.09]} rotation={[0, 0.16, -Math.PI / 2]} scale={[0.76, 0.72, 0.77]} />
      <mesh geometry={nodes.Vert007.geometry} material={materials.Книга} position={[4.29, 2.87, -3.29]} rotation={[0, -0.17, -1.68]} scale={[1.06, 1, 1.07]} />
      <mesh geometry={nodes.Vert006.geometry} material={materials.ствол} position={[0.53, 3.25, -3.41]} rotation={[0, 0.56, -Math.PI / 2]} scale={[1.06, 1, 1.07]} />
      <mesh geometry={nodes.Vert005.geometry} material={materials.шкафы} position={[3.09, 2.85, -3.25]} rotation={[0.34, 0.07, -1.34]} scale={[0.91, 0.86, 0.92]} />
      <mesh geometry={nodes.Vert004.geometry} material={materials['Книга.001']} position={[-0.66, 3.25, -3.59]} rotation={[0, 0.15, -Math.PI / 2]} scale={[1.2, 1, 1.2]} />
      <mesh geometry={nodes.Vert003.geometry} material={materials.лампа} position={[-0.96, 2.12, 2.07]} rotation={[0, 0.46, 0]} />
      <mesh geometry={nodes.Vert002.geometry} material={materials.книга} position={[-0.69, 3.25, -3.21]} rotation={[0, -0.23, -Math.PI / 2]} scale={[1.25, 1.04, 1.25]} />
      <mesh geometry={nodes.Vert001.geometry} material={materials.лампа} position={[1.28, 2.12, 3.36]} rotation={[Math.PI, -0.54, Math.PI]} />
      <mesh geometry={nodes.tree002.geometry} material={materials.ствол} position={[-3.61, 2.6, -2.62]} scale={0.32}>
        <mesh geometry={nodes.leaves002.geometry} material={materials.листва} position={[0, 2.31, -0.01]} scale={1.28} />
      </mesh>
      <mesh geometry={nodes.tree001.geometry} material={materials.ствол} position={[3.99, 1.72, 2.08]} scale={0.25}>
        <mesh geometry={nodes.leaves001.geometry} material={materials.листва} position={[0, 2.31, -0.01]} scale={1.28} />
      </mesh>
      <mesh geometry={nodes.tree.geometry} material={materials.ствол} position={[-3.71, 1.72, 3.39]} scale={0.25}>
        <mesh geometry={nodes.leaves.geometry} material={materials.листва} position={[0, 2.31, -0.01]} scale={1.28} />
      </mesh>
      <mesh geometry={nodes.Plane108.geometry} material={materials['light.001']} position={[0.26, 3.68, -4.16]} rotation={[Math.PI / 2, 0, 0]} scale={[4.89, 1, 1.17]} />
      <mesh geometry={nodes.Plane106.geometry} material={nodes.Plane106.material} position={[0.25, 3.7, -3.94]} />
      <mesh geometry={nodes.Plane105.geometry} material={materials.коробки} position={[-3.82, 0.51, 1.08]} rotation={[0, 1.44, 0]} scale={[1.12, 1.28, 0.76]} />
      <mesh geometry={nodes.Plane104.geometry} material={materials.коробки} position={[-4.07, 0.56, -0.04]} rotation={[-Math.PI, 1.43, -Math.PI]} scale={[1.12, 1.49, 0.76]} />
      <mesh geometry={nodes.Plane103.geometry} material={materials.коробки} position={[-3.78, 0.58, -1.21]} rotation={[0, 0.88, 0]} scale={[1.41, 1.54, 0.96]} />
      <mesh geometry={nodes.Plane102.geometry} material={materials.коробки} position={[-0.75, 0.44, -2.29]} />
      <mesh geometry={nodes.Plane101.geometry} material={materials.коробки} position={[4.62, 0.51, -2.31]} />
      <mesh geometry={nodes.Plane100.geometry} material={materials.коробки} position={[-2.81, 2.27, -2.48]} />
      <mesh geometry={nodes.Plane099.geometry} material={materials.коробки} position={[-3.6, 2.31, -2.48]} />
      <mesh geometry={nodes.Plane098.geometry} material={materials.коробки} position={[-3.12, 2.27, -3.17]} />
      <mesh geometry={nodes.Plane097.geometry} material={materials.коробки} position={[-4.33, 2.26, -2.49]} />
      <mesh geometry={nodes.Plane096.geometry} material={materials.коробки} position={[-4.33, 2.27, -3.19]} />
      <group position={[-1.96, 2.22, -2.79]}>
        <mesh geometry={nodes.Plane095_1.geometry} material={materials['подставка .001']} />
        <mesh geometry={nodes.Plane095_2.geometry} material={materials['Material.001']} />
      </group>
      <group position={[-2.04, 2.44, -3.39]}>
        <mesh geometry={nodes.Plane094_1.geometry} material={materials.книга} />
        <mesh geometry={nodes.Plane094_2.geometry} material={materials.листы} />
      </group>
      <group position={[-2.04, 2.44, -2.52]}>
        <mesh geometry={nodes.Plane093_1.geometry} material={materials.шкафы} />
        <mesh geometry={nodes.Plane093_2.geometry} material={materials.листы} />
      </group>
      <group position={[-2.04, 2.44, -2.88]}>
        <mesh geometry={nodes.Plane092_1.geometry} material={materials.плакат} />
        <mesh geometry={nodes.Plane092_2.geometry} material={materials.листы} />
      </group>
      <group position={[-2.04, 2.44, -3.23]}>
        <mesh geometry={nodes.Plane091_1.geometry} material={materials.Книга} />
        <mesh geometry={nodes.Plane091_2.geometry} material={materials.листы} />
      </group>
      <group position={[-2.04, 2.44, -2.71]}>
        <mesh geometry={nodes.Plane090_1.geometry} material={materials['Книга.001']} />
        <mesh geometry={nodes.Plane090_2.geometry} material={materials.листы} />
      </group>
      <group position={[-2.04, 2.44, -3.04]}>
        <mesh geometry={nodes.Plane089_1.geometry} material={materials.стул} />
        <mesh geometry={nodes.Plane089_2.geometry} material={materials.листы} />
      </group>
      <mesh geometry={nodes.Plane088.geometry} material={materials.коробки} position={[1.72, 2.56, -3.29]} scale={[1.22, 1, 1]} />
      <mesh geometry={nodes.Plane087.geometry} material={materials.коробки} position={[2.75, 2.53, -3.2]} />
      <mesh geometry={nodes.Plane086.geometry} material={materials.коробки} position={[3.71, 2.61, -3.25]} />
      <mesh geometry={nodes.Plane085.geometry} material={materials.коробки} position={[4.68, 2.56, -3.25]} scale={[1.15, 1, 1]} />
      <group position={[1.12, 0.48, 3.39]}>
        <mesh geometry={nodes.Plane084_1.geometry} material={materials.книга1} />
        <mesh geometry={nodes.Plane084_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.49, 0.5, 3.39]}>
        <mesh geometry={nodes.Plane083_1.geometry} material={materials.Книга} />
        <mesh geometry={nodes.Plane083_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.57, 0.46, 3.39]}>
        <mesh geometry={nodes.Plane082_1.geometry} material={materials.стул} />
        <mesh geometry={nodes.Plane082_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.12, 0.45, 3.39]}>
        <mesh geometry={nodes.Plane081_1.geometry} material={materials.земля} />
        <mesh geometry={nodes.Plane081_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.49, 0.41, 3.39]}>
        <mesh geometry={nodes.Plane080_1.geometry} material={materials['подставка ']} />
        <mesh geometry={nodes.Plane080_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.12, 0.41, 3.39]}>
        <mesh geometry={nodes.Plane079_1.geometry} material={materials.книга} />
        <mesh geometry={nodes.Plane079_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.12, 0.87, 3.39]}>
        <mesh geometry={nodes.Plane078_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane078_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.49, 0.88, 3.39]}>
        <mesh geometry={nodes.Plane077_1.geometry} material={materials.ствол} />
        <mesh geometry={nodes.Plane077_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.49, 0.84, 3.39]}>
        <mesh geometry={nodes.Plane076_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane076_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.12, 0.83, 3.39]}>
        <mesh geometry={nodes.Plane075_1.geometry} material={materials.горшок} />
        <mesh geometry={nodes.Plane075_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.49, 0.8, 3.39]}>
        <mesh geometry={nodes.Plane074_1.geometry} material={materials['книга.001']} />
        <mesh geometry={nodes.Plane074_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.12, 0.8, 3.39]}>
        <mesh geometry={nodes.Plane073_1.geometry} material={materials.листва} />
        <mesh geometry={nodes.Plane073_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.12, 1.26, 3.39]}>
        <mesh geometry={nodes.Plane072_1.geometry} material={materials['Книга.001']} />
        <mesh geometry={nodes.Plane072_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.49, 1.27, 3.39]}>
        <mesh geometry={nodes.Plane071_1.geometry} material={materials.книга} />
        <mesh geometry={nodes.Plane071_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.49, 1.23, 3.39]}>
        <mesh geometry={nodes.Plane070_1.geometry} material={materials.стены} />
        <mesh geometry={nodes.Plane070_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.12, 1.22, 3.39]}>
        <mesh geometry={nodes.Plane069_1.geometry} material={materials.дерево} />
        <mesh geometry={nodes.Plane069_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.49, 1.19, 3.39]}>
        <mesh geometry={nodes.Plane068_1.geometry} material={materials.шкафы} />
        <mesh geometry={nodes.Plane068_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.12, 1.19, 3.39]}>
        <mesh geometry={nodes.Plane067_1.geometry} material={materials.Книга} />
        <mesh geometry={nodes.Plane067_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.5, 1.7, 2.76]} rotation={[3.03, -1.07, 1.46]} scale={[0.37, 0.66, 0.66]}>
        <mesh geometry={nodes.Plane066_1.geometry} material={materials['Книга.001']} />
        <mesh geometry={nodes.Plane066_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.51, 1.67, 2.76]} rotation={[2.92, -1.31, 1.35]} scale={[0.37, 0.66, 0.66]}>
        <mesh geometry={nodes.Plane065_1.geometry} material={materials.шкафы} />
        <mesh geometry={nodes.Plane065_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.51, 1.64, 2.76]} rotation={[0.37, -1.42, -1.21]} scale={[0.37, 0.66, 0.66]}>
        <mesh geometry={nodes.Plane064_1.geometry} material={materials.книга} />
        <mesh geometry={nodes.Plane064_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.18, 1.87, 2.65]}>
        <mesh geometry={nodes.Plane063_1.geometry} material={materials.книга1} />
        <mesh geometry={nodes.Plane063_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.31, 1.87, 2.76]}>
        <mesh geometry={nodes.Plane062_1.geometry} material={materials.листва} />
        <mesh geometry={nodes.Plane062_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.38, 1.87, 2.3]}>
        <mesh geometry={nodes.Plane061_1.geometry} material={materials.дерево} />
        <mesh geometry={nodes.Plane061_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.25, 1.87, 2.3]}>
        <mesh geometry={nodes.Plane060_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane060_2.geometry} material={materials.листы} />
      </group>
      <group position={[1.13, 1.87, 2.3]}>
        <mesh geometry={nodes.Plane059_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane059_2.geometry} material={materials.листы} />
      </group>
      <group position={[3.87, 1.76, 3.11]} scale={[1, 1, 0.95]}>
        <mesh geometry={nodes.Plane058_1.geometry} material={materials['подставка .001']} />
        <mesh geometry={nodes.Plane058_2.geometry} material={materials['Material.001']} />
      </group>
      <group position={[3.79, 1.95, 2.88]}>
        <mesh geometry={nodes.Plane057_1.geometry} material={materials.ствол} />
        <mesh geometry={nodes.Plane057_2.geometry} material={materials.листы} />
      </group>
      <group position={[3.8, 1.95, 3.19]} scale={[1.02, 1.02, 1.3]}>
        <mesh geometry={nodes.Plane056_1.geometry} material={materials.книга} />
        <mesh geometry={nodes.Plane056_2.geometry} material={materials.листы} />
      </group>
      <group position={[3.79, 1.95, 2.71]} scale={[1, 1, 1.28]}>
        <mesh geometry={nodes.Plane055_1.geometry} material={materials.горшок} />
        <mesh geometry={nodes.Plane055_2.geometry} material={materials.листы} />
      </group>
      <group position={[3.79, 1.95, 3.03]} scale={[1, 0.86, 0.62]}>
        <mesh geometry={nodes.Plane054_1.geometry} material={materials.Книга} />
        <mesh geometry={nodes.Plane054_2.geometry} material={materials.листы} />
      </group>
      <group position={[3.79, 1.95, 3.36]} scale={[1, 1, 1.64]}>
        <mesh geometry={nodes.Plane053_1.geometry} material={materials['Книга.001']} />
        <mesh geometry={nodes.Plane053_2.geometry} material={materials.листы} />
      </group>
      <group position={[3.8, 1.95, 2.56]} scale={1.07}>
        <mesh geometry={nodes.Plane052_1.geometry} material={materials['книга.001']} />
        <mesh geometry={nodes.Plane052_2.geometry} material={materials.листы} />
      </group>
      <mesh geometry={nodes.Plane051.geometry} material={materials['подставка ']} position={[2.59, 1.65, 2.52]} rotation={[0, 0.1, 0]} />
      <mesh geometry={nodes.Plane050.geometry} material={materials['подставка ']} position={[1.72, 1.64, 2.3]} />
      <mesh geometry={nodes.Plane049.geometry} material={materials['подставка ']} position={[2.6, 1.7, 3.25]} rotation={[Math.PI, -0.06, Math.PI]} />
      <mesh geometry={nodes.Plane048.geometry} material={nodes.Plane048.material} position={[3.86, 1.29, 2.67]} scale={[1.17, 1.36, 1.17]} />
      <group position={[-3.89, 0.48, 3.39]}>
        <mesh geometry={nodes.Plane048_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane048_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.52, 0.5, 3.39]}>
        <mesh geometry={nodes.Plane047_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane047_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.43, 0.46, 3.39]}>
        <mesh geometry={nodes.Plane046_1.geometry} material={materials.ствол} />
        <mesh geometry={nodes.Plane046_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.89, 0.45, 3.39]}>
        <mesh geometry={nodes.Plane045_1.geometry} material={materials['книга.001']} />
        <mesh geometry={nodes.Plane045_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.52, 0.41, 3.39]}>
        <mesh geometry={nodes.Plane044_1.geometry} material={materials.книга1} />
        <mesh geometry={nodes.Plane044_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.89, 0.41, 3.39]}>
        <mesh geometry={nodes.Plane043_1.geometry} material={materials['Книга.001']} />
        <mesh geometry={nodes.Plane043_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.89, 0.87, 3.39]}>
        <mesh geometry={nodes.Plane042_1.geometry} material={materials.дерево} />
        <mesh geometry={nodes.Plane042_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.52, 0.88, 3.39]}>
        <mesh geometry={nodes.Plane041_1.geometry} material={materials.книга} />
        <mesh geometry={nodes.Plane041_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.52, 0.84, 3.39]}>
        <mesh geometry={nodes.Plane040_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane040_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.89, 0.83, 3.39]}>
        <mesh geometry={nodes.Plane039_1.geometry} material={materials.книга1} />
        <mesh geometry={nodes.Plane039_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.52, 0.8, 3.39]}>
        <mesh geometry={nodes.Plane038_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane038_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.89, 0.8, 3.39]}>
        <mesh geometry={nodes.Plane037_1.geometry} material={materials.шкафы} />
        <mesh geometry={nodes.Plane037_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.89, 1.26, 3.39]}>
        <mesh geometry={nodes.Plane036_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane036_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.52, 1.27, 3.39]}>
        <mesh geometry={nodes.Plane035_1.geometry} material={materials.листва} />
        <mesh geometry={nodes.Plane035_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.52, 1.23, 3.39]}>
        <mesh geometry={nodes.Plane034_1.geometry} material={materials.комп} />
        <mesh geometry={nodes.Plane034_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.89, 1.22, 3.39]}>
        <mesh geometry={nodes.Plane033_1.geometry} material={materials['книга.001']} />
        <mesh geometry={nodes.Plane033_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.52, 1.19, 3.39]}>
        <mesh geometry={nodes.Plane032_1.geometry} material={materials.стены} />
        <mesh geometry={nodes.Plane032_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.89, 1.19, 3.39]}>
        <mesh geometry={nodes.Plane031_1.geometry} material={materials.Книга} />
        <mesh geometry={nodes.Plane031_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.51, 1.7, 2.76]} rotation={[3.03, -1.07, 1.46]} scale={[0.37, 0.66, 0.66]}>
        <mesh geometry={nodes.Plane030_1.geometry} material={materials.стены} />
        <mesh geometry={nodes.Plane030_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.49, 1.67, 2.76]} rotation={[2.92, -1.31, 1.35]} scale={[0.37, 0.66, 0.66]}>
        <mesh geometry={nodes.Plane029_1.geometry} material={materials.книга} />
        <mesh geometry={nodes.Plane029_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.49, 1.64, 2.76]} rotation={[0.37, -1.42, -1.21]} scale={[0.37, 0.66, 0.66]}>
        <mesh geometry={nodes.Plane028_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane028_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.82, 1.87, 2.65]}>
        <mesh geometry={nodes.Plane027_1.geometry} material={materials.горшок} />
        <mesh geometry={nodes.Plane027_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-3.69, 1.87, 2.76]}>
        <mesh geometry={nodes.Plane026_1.geometry} material={materials.дерево} />
        <mesh geometry={nodes.Plane026_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-3.62, 1.87, 2.3]}>
        <mesh geometry={nodes.Plane025_1.geometry} material={materials.Книга} />
        <mesh geometry={nodes.Plane025_2.geometry} material={materials.листы} />
      </group>
      <group position={[-3.75, 1.87, 2.3]}>
        <mesh geometry={nodes.Plane024_1.geometry} material={materials['книга.001']} />
        <mesh geometry={nodes.Plane024_2.geometry} material={materials['Material.001']} />
      </group>
      <group position={[-3.87, 1.87, 2.3]}>
        <mesh geometry={nodes.Plane023_1.geometry} material={materials.шкафы} />
        <mesh geometry={nodes.Plane023_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-1.21, 1.95, 2.88]}>
        <mesh geometry={nodes.Plane022_1.geometry} material={materials.ствол} />
        <mesh geometry={nodes.Plane022_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-1.2, 1.95, 3.19]} scale={[1.02, 1.02, 1.3]}>
        <mesh geometry={nodes.Plane021_1.geometry} material={materials.Книга} />
        <mesh geometry={nodes.Plane021_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-1.21, 1.95, 2.71]} scale={[1, 1, 1.28]}>
        <mesh geometry={nodes.Plane020_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane020_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-1.21, 1.95, 3.03]} scale={[1, 0.86, 0.62]}>
        <mesh geometry={nodes.Plane017_1.geometry} material={materials.книга} />
        <mesh geometry={nodes.Plane017_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-1.21, 1.95, 3.36]} scale={[1, 1, 1.64]}>
        <mesh geometry={nodes.Plane016_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane016_2.geometry} material={materials.книга1} />
      </group>
      <group position={[-1.21, 1.95, 2.56]} scale={1.07}>
        <mesh geometry={nodes.Plane015_1.geometry} material={materials['книга.001']} />
        <mesh geometry={nodes.Plane015_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-1.13, 1.76, 3.11]} scale={[1, 1, 0.95]}>
        <mesh geometry={nodes.Plane014_1.geometry} material={materials['подставка .001']} />
        <mesh geometry={nodes.Plane014_2.geometry} material={materials['Material.005']} />
      </group>
      <mesh geometry={nodes.Plane014.geometry} material={materials.дерево} position={[2.59, 0.26, 2.74]} scale={[1.17, 1.36, 1.17]} />
      <mesh geometry={nodes.Plane013.geometry} material={materials['подставка ']} position={[-2.4, 1.7, 3.25]} rotation={[-Math.PI, 0.04, -Math.PI]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials.стул} position={[2.53, 1.33, 0.74]} rotation={[0, -0.3, 0]} />
      <mesh geometry={nodes.Plane011.geometry} material={materials.ручки} position={[3.06, 1.05, 1.2]} rotation={[0, -0.3, 0]} scale={[0.06, 0.13, 0.29]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials.ручки} position={[-1.82, 1.05, 1.1]} rotation={[0, 0.32, 0]} scale={[0.06, 0.13, 0.29]} />
      <mesh geometry={nodes.Plane009.geometry} material={materials.стул} position={[-2.51, 1.33, 1.03]} rotation={[0, 0.32, 0]} />
      <group position={[-4.78, 3.1, 0.23]} scale={[0.49, 0.6, 0.63]}>
        <mesh geometry={nodes.Plane008_1.geometry} material={materials.плакат} />
        <mesh geometry={nodes.Plane008_2.geometry} material={materials.монитор} />
      </group>
      <mesh geometry={nodes.Plane007.geometry} material={materials.шкафы} position={[-3.12, 1.14, -2.31]} scale={[1.05, 1, 0.87]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials.шкаф} position={[0.65, 1.7, -3.02]} scale={[1, 1, 0.95]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials.шкафы} position={[3.18, 1.29, -3.03]} scale={[2.03, 1.08, 0.4]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['подставка ']} position={[-3.28, 1.64, 2.3]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['подставка ']} position={[-2.41, 1.65, 2.52]} rotation={[0, -0.07, 0]} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[-1.14, 1.29, 2.67]} scale={[1.17, 1.36, 1.17]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.дерево} position={[-2.41, 0.26, 2.74]} rotation={[0.01, 0.07, 0.04]} scale={[1.17, 1.36, 1.17]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.стены} position={[-0.58, 2.25, -0.44]} />
      <group position={[2.65, 2.22, 3.32]} rotation={[Math.PI, -0.06, Math.PI]} scale={[1.29, 1.29, 1]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.комп} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.монитор} />
      </group>
      <group position={[-2.36, 2.22, 3.32]} rotation={[-Math.PI, 0.04, -Math.PI]} scale={[1.29, 1.29, 1]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.комп} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.монитор} />
      </group>
      <group position={[-3.61, 2.62, -2.62]} scale={1.64}>
        <mesh geometry={nodes.Circle008_1.geometry} material={materials.горшок} />
        <mesh geometry={nodes.Circle008_2.geometry} material={materials.земля} />
      </group>
      <mesh geometry={nodes.Circle007.geometry} material={materials.лампа} position={[1.39, 2.36, 3.29]} rotation={[-Math.PI, -0.54, -2.76]} scale={1.67} />
      <mesh geometry={nodes.Circle006.geometry} material={materials['подставка ']} position={[1.38, 1.66, 3.29]} rotation={[Math.PI, -0.54, Math.PI]} />
      <group position={[3.99, 1.74, 2.08]} scale={1.28}>
        <mesh geometry={nodes.Circle005_1.geometry} material={materials.земля} />
        <mesh geometry={nodes.Circle005_2.geometry} material={materials.горшок} />
      </group>
      <mesh geometry={nodes.Circle004.geometry} material={materials.лампа} position={[-1.08, 2.36, 2.13]} rotation={[0, 0.46, 0.38]} scale={1.67} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['подставка ']} position={[-1.07, 1.66, 2.13]} rotation={[0, 0.46, 0]} />
      <group position={[-3.71, 1.74, 3.39]} scale={1.28}>
        <mesh geometry={nodes.Circle002_1.geometry} material={materials.горшок} />
        <mesh geometry={nodes.Circle002_2.geometry} material={materials.земля} />
      </group>
      <mesh geometry={nodes.Circle001.geometry} material={materials.ручки} position={[2.46, 0.95, 0.96]} rotation={[0, -0.3, 0]} />
      <mesh geometry={nodes.Circle.geometry} material={materials.ручки} position={[-2.49, 0.95, 1.15]} />
    </group>
  )
}

useGLTF.preload('/office2.glb')
